server:
  port: 18888
spring:
  application:
    name: zuul-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        serviceName: ${spring.application.name}
cd:
  oauth2:
    token:
      store:
        type: resJwt
  security:
    ignore:
      # 忽略认证的地址
      httpUrls: >
        /api-auth/oauth/**,
        /api-user/users-anon/**,
        /login.html,
        /user/login
      # 配置只认证登录，登录后所有角色都能访问的url
      menusPaths: /api-user/menus/current
    auth:
      # 配置必需认证的url
      httpUrls: >
        /api-auth/clients/**,
        /api-auth/tokens/**
      #是否开启url级别权限
      urlEnabled: true
zuul:
  ribbon-isolation-strategy: thread
  ribbon:
    eager-load:
      enabled: true
    threadPool:
      useSeparateThreadPools: true
      threadPoolKeyPrefix: zuul-gateway
  #关闭重试
  retryable: false
  #/oauth/token需要请求头处理
  sensitive-headers:
  ignored-headers: Access-Control-Allow-Credentials,Access-Control-Allow-Origin,Access-Control-Allow-Methods
  add-host-header: true
  routes:
    auth:
      path: /api-auth/**
      service-id: cd-auth
      strip-prefix: true
      custom-sensitive-headers: true
    auth-login-page:
      path: /login.html
      service-id: cd-auth
      strip-prefix: true
      custom-sensitive-headers: true
    auth-login-process:
      path: /user/login
      service-id: cd-auth
      strip-prefix: true
      custom-sensitive-headers: true
    auth-login-token:
      path: /oauth/token
      service-id: cd-auth
      strip-prefix: true
      custom-sensitive-headers: true
    auth-login-authorize:
      path: /oauth/authorize
      service-id: cd-auth
      strip-prefix: true
      custom-sensitive-headers: true
    auth-check-process:
      path: /oauth/check_token
      service-id: cd-auth
      strip-prefix: true
      custom-sensitive-headers: true
    user:
      path: /api-user/**
      service-id: user-center
      strip-prefix: true
      custom-sensitive-headers: true
  ssl-hostname-validation-enabled: false
feign:
  hystrix:
    enabled: false